### PR TITLE
Add Spanish Translation

### PR DESCRIPTION
**Pull request by Nemesti**
Add Spanish Translation

### CODE REVIEW

**Review by zalexki — APPROVED** [review]

**Comment by zalexki** [comment]
develop branch has been rewritten can you rebase @Nemesti ? thx.

**Comment by Nemesti** [comment]
Sorry, i've problems to update my fork. As soon as i can, i update it

**Comment by zalexki** [comment]
there is only one commit i'll recreate it later if you want, fyi : https://help.github.com/articles/syncing-a-fork/

**Comment by zalexki** [comment]
Done with #348

**Pull request closed without merging**
