### PR TITLE
Spanish Add and Fix

### PR DESCRIPTION
**Pull request by Nemesti**
Spanish Add and Fix

### CODE REVIEW

**Comment by zalexki** [comment]
Looks mergeable @StefArma @Barbolani77 ?

**Comment by StefArma** [comment]
Yes, i was waiting to merge, maybe i can create a develop branch where we can merge theese, when 1.8.1 will be complete then we merge into master

**Review by StefArma — APPROVED** [review]
Good for me! Thanks Namesti for all your work.. i was waiting to reorganize the workflow, we're getting into it ;)

**Review by zalexki — APPROVED** [review]

**Comment by Nemesti** [comment]
No problem StefArma, I'll continue reviewing files to continue with the translation

**Pull request merged**
