### PR TITLE
CIV cars tweaks

### PR DESCRIPTION
**Pull request by IrLED**
Civ cars go further (2-5km), that will make traffic less intensive in towns concentrated area[114140].
Cars wait less when reaching WP (less possibility for traffic jam in the town center)
You can find traffic in remote areas (like NW of Altis)
Fuel amount for civ cars varies 5-50%
Cars randomized initialization as the possible solution to synchronize appearance on different clients.

### CODE REVIEW

**Comment by Barbolani77** [comment]
Make sure those cars have different destination than the town center. That's probably the problem of those traffic jams. Pick a road segment from the roadsDB related to the destination city

**Comment by StefArma** [comment]
no traffic jam anymore, that's sure .. maybe some tweaks to make the traffic remaining around... after 10 minutes all cars are far away in remote places

**Comment by Barbolani77** [comment]
Shouldnt as the wypoints are cycled, if I remember well

**Comment by StefArma** [comment]
true, however cycling in town was chaotic.. better to cycle them to far away towns

traffic is nice on our version now... just tweaking that distance. Hardly see explosions

**Comment by Barbolani77** [comment]
Regarding explosions, it should have nothing with civ patrols but with problematic road positions (with a house, streetlamp or whatever thing which, when the script moves the truck to a "parked" position, explodes).

I have an idea, lets clean that DB.

Make a script that creates a truck (in the way Antistasi does) on each road position for, lets say 5 seconds.

The truck exploded? Remove that position. Didn't? Add to the DB.

Will solve the problem and the roads DB will be lighter, more performance :)

**Comment by StefArma** [comment]
Explosions about civis driving into something, spawning is fine

**Comment by Sparker95** [comment]
Well, if they explode too much we could give them a custom handleDamage event handler so that they don't get damage from collisions.

**Comment by StefArma** [comment]
hold on, i'm saying we've no longer explosion or intense traffic...

my point is that i reduced the distance they travel (it was 5km) now it's 2km otherwise the traffic was getting too low that after 10 mins there won't be cars around

**Pull request merged**
