### PR TITLE
Russian.vn

### PR DESCRIPTION
**Pull request by VelvetNight**

### CODE REVIEW

**Comment by StefArma** [comment]
Wow that's huge! Basically now we're ready to translate to multiple languages! Don't know how to say properly thanks!

**Comment by AlexTriada** [comment]
This is a misunderstanding, you do not need to add this pull request yet

**Comment by StefArma** [comment]
lol i made forumpost, added credits etc ahhaah

**Comment by AlexTriada** [comment]
I'll check everything tomorrow and get the verified version

**Comment by StefArma** [comment]
no hurry, i'll wait for it for further steamrelease... i still wanna fix the airdrop and airassault if i manage

**Pull request merged**
