### PR TITLE
RU translate

### PR DESCRIPTION
**Pull request by alexUnd**

### CODE REVIEW

**Comment by StefArma** [comment]
Another great effort thanks a lot!

I'll check code syntax, definitly gonna be lovely for steam release!

**Comment by alexUnd** [comment]
in game
bugs in menu (map menu) with the display (it is not displayed from the beginning of the text)
sections:
1) Antistasy features (Функции Antistasi) ---> Undercover (Инкогнито)
2) Antistasy features (Функции Antistasi) ---> Class System (Система классов)
3) Commander Options (Командование) ---> Emplacements (Позиции FIA)

**Comment by alexUnd** [comment]
i think this is the last
improoved 27-01#2

**Comment by StefArma** [comment]
Nice! Sadly there are many conflicts and i might be part of the cause... so merging will take longer

**Comment by AlexTriada** [comment]
I could help with the issue of preparing these changes and resolving merger conflicts, let alexUnd send their changes to my repository.

**Comment by alexUnd** [comment]
<Original>No LCS available this decade, QRF is restricted to land.</Original>		  			    
 <Russian>В этом десятилетии нет LCS, QRF ограничен землей.</Russian>   :))
Никак не могу понять что это?

**Comment by alexUnd** [comment]
привет ! Добавил файл в твой репозиторий triada_russian_fixes. Правильно?

**Pull request closed without merging**
