### PR TITLE
HQ veh buy & templates rework

### LINKED ISSUE #126: Issue with disappearing objectives when doing multiple Camp setups
Its possible to have more than one camp setup, ie create a camp one place, then create a second before the first is completed. When this occurs, starting the second camp setup mission seems to make the first disappear, and you're left with a camp squad with nothing to do. 

Obvious solution for end-user is to not do this, but maybe consider just locking off the encampment mission/function if one is already active.

### PR DESCRIPTION
**Pull request by StefArma**
Fix #126

### CODE REVIEW

**Comment by zalexki** [comment]
Yesterday i noticed that civi heli is the MD-500 for no rhs and a fucking big one for RHS can we use the MD-500 for RHS too in order to be consistent between mod version ?

**Comment by StefArma** [comment]
Agree

**Comment by StefArma** [comment]
Actually... the big helicopter is better for moving purpose, that small one has pilot + 3 seats only.. best would be using the IDAP helicopter in vanilla.. however that's dlc dependent so we can't :(

**Comment by zalexki** [comment]
In a roleplay/realistic way the MD-500 make way more sens than a big fucking cow in the air.
It will give players the ability to make close insertion of objective without being detected only if the pilot is good enough (thx @wurzel0701 for the air control feature).
This will still give the minor possibility to use helis in antistasi but at a 5000$ cost (which is high enough i think) and with a good training or you'll quickly get fucked by AAs.

**Pull request merged**
