### PR TITLE
Tweaked aircontrol to 2 km and reveal planes

### PR DESCRIPTION
**Pull request by wurzel0701**
Tweaked the spawn of AA units to 2 km and revealed planes to AA guys

### CODE REVIEW

**Comment by zalexki** [comment]
Need rebase on develop.

**Comment by wurzel0701** [comment]
Perhaps recreating it will be easier :D

**Comment by zalexki** [comment]
as you wish :) and remember that air control is not in develop anymore.
So yeah actually i suggest you to create another branch and cherry-pick what you need

**Comment by zalexki** [comment]
Need recreation of branch.

**Pull request closed without merging**
