### PR TITLE
Headless client infrastructure rework + coarse balancer

### PR DESCRIPTION
**Pull request by IrLED**
HCs now register/deregister to worker pool (server is permanent worker).
Current coarse balancing is done by randomly picking the worker from pool.
Current limitation - if event of disconnecting worker occurs, AI that changed locality will become stuck,
 and destruction cycle will be lost (subject to next improvements).

_BTW the code has already been running on US official under `rc6===HC-balancer` label. so far so good_
Script[local] to check the load on workers (worker 2 - server)
```
{   
	{ 
		[[remoteExecutedOwner], 
			{ 
				[format["Worker:%1, FPS:%2, units:%3", clientOwner, diag_fps, {local _x}count allUnits]] remoteExec ["systemchat", _this select 0];   
			} 
		] 
		remoteExec ["call", _x];   
	}forEach workerArray; 
}   
remoteExec ["call", 2];
```

### CODE REVIEW

**Comment by StefArma** [comment]
Wow! you did it!

**Comment by StefArma** [comment]
Ok so, i'd leave to server a maximum amount of AI of 50 if is possible... i'd prefer the server use the CPU to handle players and HC boradcasting... I'll buy more headlessclients so we can put the load on them

**Comment by StefArma** [comment]
Very nice

**Comment by IrLED** [comment]
Fixed the worker strategy for the cases, when it's called from client (which is not very right). but fallback works. E.g. USMC Resupply + QRF were affected

**Comment by IrLED** [comment]
balancer is now configured with ratio 1:2 (e.g. server - 50AI, HC1 - 100AI , HC2-100AI, HC3 -100AI)

**Comment by IrLED** [comment]
As a plus - fix of NATO ammo crate dropping beneath the ground.
Fixes #143

**Pull request merged**
