### PR TITLE
1.8.0.1

### PR DESCRIPTION
**Pull request by zalexki**
As we seen with @StefArma develop is gonna be the pre-release branch and master the production ready/release one (when it's tested and should be bug free).

In that in mind i'm pretty sure we can already merge this branch into develop in order to make some pre-release 1.8.0.1-rc1 (following @IrLED tags management).

### CODE REVIEW

**Comment by StefArma** [comment]
Still working here, probably tomorrow gonna have a sort of rc1

**Comment by StefArma** [comment]
I'm going to extract some stuff from this one and make a new pullrequest

**Comment by zalexki** [comment]
Actually, we shouldn't work like that.
Every release is a combination of PR (aka feature/fix). 
Before merging every PR should be tested and approved.
Once a few PRs are merged into develop we create a new tag (pre-release, release candidate whatever you want to call it) pointing on develop branch and listing every one of this PR. (easier to manage)

If you really want you can create this kind of branch but at least name it `next release candidate` instead of a tag name like `1.8.x.x`, you can eventually add the tag name into the PR title/description because it is easy to change but the name branch should not have tag name.

Imagine that we have an awesome super mega important fix that will been merged to develop before this release you are preparing, if you stay with a tag name your branch name will be very confusing.

**Comment by StefArma** [comment]
Sure this was a quick attempt for an event.. not gonna happen again...

I gonna need to learn about rebase: 

https://github.com/A3Antistasi/antistasiofficial/commit/997e1eb28a699afdd998f3cd03e8df6d1433a4e0
this need to be reverted in master and all the branches

That fix will be needed but it will make hardtime for all test if i let it it now because it generate an incompatibility with "1.8.0 release-version" save

**Pull request closed without merging**
